#!/bin/bash
# Delete all branches that have been merged to master && push deletes to remote origin

CHECK_ORIGIN=$(git remote -v | grep '^origin.\+(push)$')
if [ -z "$CHECK_ORIGIN" ]; then
	echo "You need to be in a git repo with a pushable \"origin\" remote!"
	exit 1
fi

git branch | grep -vP '\bmaster\b|^\*' | \
	while read -r BRANCH; do
		ST=$(git branch -d "$BRANCH" 2>&1)
		if [ $? -eq 0 ]; then
			echo -n "Pruned \"$BRANCH\"; removing from origin..."
			RST=$(git push origin ":$BRANCH" 2>&1)
			if [ $? -eq 0 ]; then
				echo " Removed."
			else
				echo
				echo "Branch \"$BRANCH\" not removed from origin: $RST"
			fi
		else
			ST=$(echo "$ST" | head -n 1 | sed 's/error: //')
			echo "Branch \"$BRANCH\" not removed: $ST"
		fi
	done
